const ACTION_TYPES = {
    FETCH_USERS:'FETCH_USERS',
    FETCH_USERS_SUCCESS:'FETCH_USERS_SUCCESS',
    FETCH_USERS_FAIL:'FETCH_USERS_FAIL',
    ADD_USER:'ADD_USER',
    EDIT_USER:'EDIT_USER',
    DELETE_USER:'DELETE_USER'
}

export default ACTION_TYPES