const ACTION_TYPES = {
    // types for users CRUD
    FETCH_USERS: 'FETCH_USERS',
    FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',
    FETCH_USERS_FAIL: 'FETCH_USERS_FAIL',
    ADD_USER: 'ADD_USER',
    EDIT_USER: 'EDIT_USER',
    DELETE_USER: 'DELETE_USER',

    // sorting
    SORT_BY_ID: 'SORT_BY_ID',
    SORT_BY_NAME: 'SORT_BY_NAME',
    SORT_BY_EMAIL: 'SORT_BY_EMAIL',

    // handling sidebar
    OPEN_SIDE_BAR:'OPEN_SIDE_BAR',
    CLOSE_SIDE_BAR:'CLOSE_SIDE_BAR'

}

export default ACTION_TYPES